# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      TORCH_TEST: 1
      TORCH_INSTALL: 1

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        id: setup-r
        with:
          r-version: 'release'
          use-public-rspm: true

      - name: Install remotes
        run: install.packages("remotes")

      - name: Install Package + deps
        run: remotes::install_local(dependencies = TRUE, force = TRUE)
        shell: Rscript{0}

      - name: Install Miniconda
        run: reticulate::install_miniconda()
        shell: Rscript {0}

      - name: Install Tensorflow + Keras deps
        run: keras::install_keras(tensorflow = 'default-cpu')
        shell: Rscript {0}

      - name: Check if torch is installed
        run: |
          library(torch)
          if (!torch_is_installed()) {
            print("Torch is not installed!")
            install_torch()
          }
        shell: Rscript {0}

      - name: Test coverage
        run: |
          covr::codecov(
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(Sys.getenv("RUNNER_TEMP"), "package")
          )
        shell: Rscript {0}

      - name: Show testthat output
        if: always()
        run: |
          ## --------------------------------------------------------------------
          find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package
